# Generated by Django 3.0.3 on 2020-03-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=1000)),
                ('Discription', models.CharField(default=' ', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(default=' ', upload_to='sqlapp/image')),
                ('Discount', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
                ('Discription', models.CharField(max_length=5000)),
                ('Type', models.CharField(max_length=100)),
                ('Key_Features', models.CharField(max_length=5000)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('Specification_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=100)),
                ('Warranty', models.IntegerField(default=0)),
                ('Batteries_no', models.IntegerField(default=0)),
                ('Weight', models.IntegerField(default=0)),
                ('Depth', models.IntegerField(default=0)),
                ('Battery_Type', models.CharField(max_length=500)),
                ('Color', models.CharField(max_length=500)),
                ('Package_Content', models.CharField(max_length=5000)),
                ('Accuracy', models.DecimalField(decimal_places=5, max_digits=50)),
                ('Weighing_Capacity', models.IntegerField(default=0)),
                ('Display_Size', models.IntegerField(default=0)),
                ('Height', models.IntegerField(default=0)),
                ('Width', models.IntegerField(default=0)),
                ('Diameter', models.IntegerField(default=0)),
                ('Display_Type', models.CharField(max_length=500)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseapp.Product')),
            ],
        ),
    ]
