# Generated by Django 3.0.3 on 2020-03-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default=' ', upload_to='databaseapp/image'),
        ),
    ]
